"""Correct single-token case mismatches against Brown (fixes #13, #28).

#13 and #28 both claimed a large number of capitalization divergences
against `nltk.corpus.brown` (152 and 976 respectively) and #28 settled
on a policy of unconditional both-directions alignment with Brown. But
`nltk.corpus.brown`'s own tokenized rendering isn't reliable ground
truth for this repo (see #14, #18, PR #19): checking #28's own cited
examples against `src/semcor/brown-nolines.txt` disproves the premise
-- e.g. `brown-nolines.txt` already has `"Twilight of Southern
Regionalism"` and `"the Prix de Rome"`, lowercase, matching what this
corpus already has, not the Title Case #28 attributed to Brown.

Re-deriving the real scope against `brown-nolines.txt` (word-level diff,
same method `semcor-compare-brown-nolines` uses) and verifying each
candidate individually finds only 8 genuine instances, in both
directions (some already lowercase in this corpus need capitalizing,
some already capitalized need lowercasing) -- covering both issues'
actual intent, not just #13's narrower quote-terminal trigger. See the
correction comments on #13/#28.

Every one of the 8 is a single-token, same-length (case-fold-preserving)
surface substitution -- token *count* and every span are completely
unaffected, since swapping a character's case never changes string
length. `lemmas` is updated too, but only where the current entry is an
exact, case-sensitive copy of the token's *old* (wrong-case) surface --
several of these already have a differently-cased or entirely different
lemma (a lowercase sense-form, or a generic lemma like `person`), which
is left untouched. `oewn_key`/`wn16_key`/`wn30_key` never change: sense
keys are already spec'd to ignore surface casing, same precedent as
#43/#51.

`src/semcor/case-mismatch-fixes.yaml` lists all 8 confirmed
`{file, sentence, index, replacement}` fixes -- hand-verified against
`brown-nolines.txt` individually rather than generated by an
unsupervised scan, given how small the set is. This script has no NLTK
dependency and just applies that manifest.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

import yaml

from semcor.validate import DATA_DIR, _YAML_LOADER, find_yaml_files

MANIFEST_PATH = Path(__file__).resolve().parent / "case-mismatch-fixes.yaml"

_DOC_BOUNDARY = re.compile(r"(?m)^(\S+):[ \t]*$")
_TEXT_BLOCK = re.compile(r"(?m)^    text: .*?(?=\n    tokens: )", re.S)
_LEMMAS_LINE = re.compile(r"(?m)^    lemmas: (\[.*\])$")

_WIDTH = 10**9


def load_manifest(path: Path = MANIFEST_PATH) -> dict[str, dict[str, list[tuple[int, str]]]]:
    """Return {filename: {sentence_id: [(index, replacement), ...]}}."""
    with path.open("r", encoding="utf-8") as f:
        entries = yaml.safe_load(f) or []
    by_file: dict[str, dict[str, list[tuple[int, str]]]] = defaultdict(lambda: defaultdict(list))
    for entry in entries:
        filename = Path(entry["file"]).name
        by_file[filename][entry["sentence"]].append((entry["index"], entry["replacement"]))
    return by_file


def fix_sentence(sent: dict, fixes: list[tuple[int, str]]) -> dict | None:
    """Apply a sentence's (index, replacement) case-mismatch fixes.

    Returns a new sentence dict, or None if every fix was already
    applied (e.g. a second run).
    """
    text = sent["text"]
    tokens = sent["tokens"]
    lemmas = sent["lemmas"]

    applied = []  # (index, replacement, old_surface)
    for index, replacement in fixes:
        s, e = tokens[index]
        old = text[s:e]
        if old == replacement:
            continue  # already fixed -- no-op
        if old.lower() != replacement.lower():
            raise RuntimeError(
                f"manifest entry (index={index}, replacement={replacement!r}) "
                f"doesn't match current surface {old!r} -- refusing to edit"
            )
        applied.append((index, replacement, old))

    if not applied:
        return None

    new_text = text
    new_lemmas = list(lemmas)
    for index, replacement, old in applied:
        s, e = tokens[index]
        new_text = new_text[:s] + replacement + new_text[e:]
        if lemmas[index] == old:
            new_lemmas[index] = replacement

    new_sent = dict(sent)
    new_sent["text"] = new_text
    new_sent["lemmas"] = new_lemmas
    return new_sent


def _dump_str(value: str) -> str:
    return yaml.safe_dump(value, default_style='"', allow_unicode=True, width=_WIDTH).rstrip("\n")


def _render_str_list(key: str, values: list[str]) -> str:
    body = ", ".join(_dump_str(v) for v in values)
    return f"    {key}: [{body}]"


def _render_text(text: str) -> str:
    text_yaml = yaml.safe_dump(text, default_style="'", allow_unicode=True, width=_WIDTH).rstrip("\n")
    return f"    text: {text_yaml}"


def fix_file(path: Path, manifest: dict, dry_run: bool = False) -> list[str]:
    """Apply this file's manifested case-mismatch corrections.

    Returns the list of sentence IDs changed (or that would change, if
    `dry_run`).
    """
    file_fixes = manifest.get(path.name)
    if not file_fixes:
        return []

    with path.open("r", encoding="utf-8") as f:
        data = yaml.load(f, Loader=_YAML_LOADER)

    changed: dict[str, dict] = {}
    for sid, fixes in file_fixes.items():
        sent = data.get(sid)
        if not isinstance(sent, dict):
            raise RuntimeError(f"{path}: manifested sentence {sid!r} not found")
        new_sent = fix_sentence(sent, fixes)
        if new_sent is not None:
            changed[sid] = new_sent

    if not changed or dry_run:
        return list(changed)

    raw = path.read_text(encoding="utf-8")
    matches = list(_DOC_BOUNDARY.finditer(raw))
    bounds = [m.start() for m in matches] + [len(raw)]
    doc_ids = list(data.keys())
    if len(matches) != len(doc_ids):
        raise RuntimeError(
            f"{path}: found {len(matches)} top-level blocks in raw text but "
            f"{len(doc_ids)} keys when parsed -- refusing to edit"
        )

    pieces = []
    for i, doc_id in enumerate(doc_ids):
        chunk = raw[bounds[i] : bounds[i + 1]]
        if doc_id in changed:
            new_sent = changed[doc_id]
            text_repl = _render_text(new_sent["text"])
            chunk, n = _TEXT_BLOCK.subn(lambda m: text_repl, chunk, count=1)
            if n != 1:
                raise RuntimeError(f"{path}: could not find text block for {doc_id!r}")
            lemmas_repl = _render_str_list("lemmas", new_sent["lemmas"])
            chunk, n = _LEMMAS_LINE.subn(lambda m: lemmas_repl, chunk, count=1)
            if n != 1:
                raise RuntimeError(f"{path}: could not find lemmas line for {doc_id!r}")
        pieces.append(chunk)

    path.write_text("".join(pieces), encoding="utf-8")
    return list(changed)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Correct single-token case mismatches against Brown "
        "in data/*.yaml (fixes #13, #28), per case-mismatch-fixes.yaml."
    )
    parser.add_argument(
        "paths",
        nargs="*",
        type=Path,
        help="Files or directories to update (default: data/)",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=MANIFEST_PATH,
        help="Manifest file to read (default: %(default)s)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Report what would change without writing anything",
    )
    args = parser.parse_args()

    if args.paths:
        files = []
        for p in args.paths:
            files.extend(sorted(p.rglob("*.yaml")) if p.is_dir() else [p])
    else:
        files = find_yaml_files(DATA_DIR)

    manifest = load_manifest(args.manifest)

    total_sentences = 0
    changed_files = 0
    for path in files:
        changed = fix_file(path, manifest, dry_run=args.dry_run)
        if changed:
            changed_files += 1
            total_sentences += len(changed)

    verb = "Would fix" if args.dry_run else "Fixed"
    print(f"{verb} {total_sentences} sentence(s) across {changed_files} file(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
